server:
  port: 8082

springdoc:
  swagger-ui:
    path: "/api-docs"

spring:
  datasource:
    url: jdbc:h2:mem:timefolddb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

timefold:
  solver:
    termination:
      spent-limit: 3s