spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: password123
      database: customer
      uri: mongodb://root:password123@localhost:27017/
      authentication-database: admin
  jpa:
    hibernate:
      ddl-auto: update